### PR TITLE
Added bash for easier container inspection.

### PR DESCRIPTION
**Pull request by carlba**

### CODE REVIEW

**Comment by xagaba** [comment]
Do you know that Alpine Linux containers use 'ash' as default shell ?
You can use it for container inspection
docker exec -it snapraid ash

**Comment by carlba** [comment]
I had no idea :) That makes this redundant.

**Comment by carlba** [comment]
What about the output from the cron job I just see one line in the log of the container

**Comment by carlba** [comment]
screenshot 2018-04-12 20 18 08

**Comment by xagaba** [comment]
I'm getting this in docker container logs
```
crond: crond (busybox 1.27.2) started, log level 6
crond: USER root pid  49 cmd /usr/bin/python /app/snapraid-runner/snapraid-runner.py -c /config/snapraid-runner.conf
2018-04-12 03:00:01,684 [INFO  ] ============================================================
2018-04-12 03:00:01,684 [INFO  ] Run started
2018-04-12 03:00:01,684 [INFO  ] ============================================================
2018-04-12 03:00:01,685 [INFO  ] Running diff...
2018-04-12 03:00:01,706 [OUTPUT] Loading state from /mnt/data01/snapraid.content...
2018-04-12 03:00:33,151 [OUTPUT] Comparing...
.
.
.
2018-04-12 03:07:45,899 [OUTPUT] Initializing...
2018-04-12 03:08:14,382 [OUTPUT] Scrubbing...
2018-04-12 03:08:15,612 [OUTPUT] Using 72 MiB of memory for 32 blocks of IO cache.
2018-04-12 03:08:17,749 [OUTPUT] Nothing to do
2018-04-12 03:08:18,290 [INFO  ] ************************************************************
2018-04-12 03:08:18,291 [INFO  ] All done
2018-04-12 03:08:18,291 [INFO  ] Run finished successfully
```

**Comment by carlba** [comment]
Hmm why do I get the incomplete logs? That is odd.

**Comment by carlba** [comment]
Do you have a logfile specified?

**Comment by carlba** [comment]
in the snapraid-runner config-file

**Comment by carlba** [comment]
Alright it seems like I caused the issues warranting this PR so I will close it for now :)

**Pull request closed without merging**
